# XGBoost Model for PL-S5E6

Feature Engineering idea : [EDA Notebook](https://www.kaggle.com/code/suhyukchoi/pl-s5e6-eda-notebook)

In [19]:
VER = 1

# Setup for Training

## Loading Libraries

In [1]:
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, LabelEncoder, OrdinalEncoder
from itertools import combinations
import gc
import optuna

/home/imcsh123/.conda/envs/rapids-25.04/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Loading Datasets

In [2]:
train = pd.read_csv("data/train.csv", index_col = 0)
test = pd.read_csv("data/test.csv", index_col = 0)
org_train = pd.read_csv("data/Fertilizer Prediction.csv")

train = pd.concat([train, org_train], axis=0, ignore_index=True)

train.head()

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,37,70,36,Clayey,Sugarcane,36,4,5,28-28
1,27,69,65,Sandy,Millets,30,6,18,28-28
2,29,63,32,Sandy,Millets,24,12,16,17-17-17
3,35,62,54,Sandy,Barley,39,12,4,10-26-26
4,35,58,43,Red,Paddy,37,2,16,DAP

## Check Dataset

### Train Dataset

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850000 entries, 0 to 849999
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Temparature      850000 non-null  int64
 1   Humidity         850000 non-null  int64
 2   Moisture         850000 non-null  int64
 3   Soil Type        850000 non-null  object
 4   Crop Type        850000 non-null  object
 5   Nitrogen         850000 non-null  int64
 6   Potassium        850000 non-null  int64
 7   Phosphorous      850000 non-null  int64
 8   Fertilizer Name  850000 non-null  object
dtypes: int64(6), object(3)
memory usage: 58.4+ MB

In [4]:
train.describe()

,Temparature,Humidity,Moisture,Nitrogen,Potassium,Phosphorous
count,850000.000000,850000.000000,850000.000000,850000.000000,850000.000000,850000.000000
mean,31.503534,61.032665,45.162887,23.081215,9.477581,21.066198
std,4.024909,6.648149,11.799929,11.219842,5.765965,12.352064
min,25.000000,50.000000,25.000000,4.000000,0.000000,0.000000
25%,28.000000,55.000000,35.000000,13.000000,4.000000,10.000000
50%,32.000000,61.000000,45.000000,23.000000,9.000000,21.000000
75%,35.000000,67.000000,55.000000,33.000000,14.000000,32.000000
max,38.000000,72.000000,65.000000,42.000000,19.000000,42.000000

In [5]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 250000 entries, 750000 to 999999
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Temparature  250000 non-null  int64
 1   Humidity     250000 non-null  int64
 2   Moisture     250000 non-null  int64
 3   Soil Type    250000 non-null  object
 4   Crop Type    250000 non-null  object
 5   Nitrogen     250000 non-null  int64
 6   Potassium    250000 non-null  int64
 7   Phosphorous  250000 non-null  int64
dtypes: int64(6), object(2)
memory usage: 17.2+ MB

In [6]:
test.describe()

,Temparature,Humidity,Moisture,Nitrogen,Potassium,Phosphorous
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.00000
mean,31.491648,61.045120,45.190444,23.139612,9.487764,21.12206
std,4.024093,6.636372,11.793167,11.215956,5.766860,12.38087
min,25.000000,50.000000,25.000000,4.000000,0.000000,0.00000
25%,28.000000,55.000000,35.000000,13.000000,4.000000,10.00000
50%,31.000000,61.000000,45.000000,23.000000,10.000000,21.00000
75%,35.000000,67.000000,55.000000,33.000000,14.000000,32.00000
max,38.000000,72.000000,65.000000,42.000000,19.000000,42.00000

- No Missing Values. Don't need to impute.

## Define Useful Methods/Variables

### Variables

In [7]:
TARGET = 'Fertilizer Name'
COLUMNS = train.columns.tolist()
QUAN_COLUMNS = [col for col in train.columns if train[col].dtype != 'object' and col != TARGET]
CAT_COLUMNS = [col for col in train.columns if train[col].dtype == 'object' and col != TARGET]

print("Total Columns:" ,COLUMNS)
print('Target column:', TARGET)
print('Quantitative columns:', QUAN_COLUMNS)
print('Categorical columns:', CAT_COLUMNS)

Total Columns: ['Temparature', 'Humidity', 'Moisture', 'Soil Type', 'Crop Type', 'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name']
Target column: Fertilizer Name
Quantitative columns: ['Temparature', 'Humidity', 'Moisture', 'Nitrogen', 'Potassium', 'Phosphorous']
Categorical columns: ['Soil Type', 'Crop Type']

### Methods

In [8]:
def FE_for_gbdt(train, test):
    dfs = [train, test]
    
    # 1. Categorical Columns Encoding.
    
    for df in dfs:
        new_CAT_COLUMNS = set() # For Uniqueness.
        '''
        1.  Add New Cateogical Column Here!
            You need to add new categorical columns into new_CAT_COLUMNS list to successfully conduct Interaction terms.
        '''
        # ========================================
        
        df["Soil Type_Crop Type"] = df["Soil Type"].astype(str) + "_" + df["Crop Type"].astype(str)
        new_CAT_COLUMNS.add("Soil Type_Crop Type")

        # =========================================
        '''
        2.  Add 2-level Interaction term between Categorical Columns.
            Automatically conducted.
        

        comb = list(combinations(CAT_COLUMNS + list(new_CAT_COLUMNS) + ["Temparature"], 2))
        
        for c1, c2 in comb:
            new_col = f"{c1}_{c2}"
            df[new_col] = df[c1].astype(str) + "_" + df[c2].astype(str)
            new_CAT_COLUMNS.add(new_col)
        '''
    # Update CAT_COLUMNS.
    CAT_COLUMNS.extend(list(new_CAT_COLUMNS))

    # Ordinal Encoding for Categorical Columns.
    for col in CAT_COLUMNS:
        le = OrdinalEncoder()
        train[col] = le.fit_transform(pd.DataFrame(train[col].astype(str)))
        test[col] = le.transform(pd.DataFrame(test[col].astype(str)))

    # 2. Quantitative Columns Encoding.
    for df in dfs:
        new_QUAN_COLUMNS = set()  # For Uniqueness.
        new_RATIO_COLUMNS = set()  # To avoid duplicate columns in interaction feature step (ex : (c1/c2) * c2 == c1), we need to specify ratio columns.
        
        '''
        1.  Add New Quantitative Column Here!
            You need to add new quantitative columns into new_QUAN_COLUMNS list to successfully conduct Interaction terms.
        
        # ========================================
        # Add Total_Nutrients Feature.
        df["Total_Nutrients"] = df["Nitrogen"] + df["Phosphorous"] + df["Potassium"]
        new_QUAN_COLUMNS.add("Total_Nutrients")
        
        # Add Nutrients Ratio Feature.
        comb = list(combinations(["Nitrogen", "Phosphorous", "Potassium"], 2))
        
        for c1, c2 in comb:
            new_col = f"{c1}/{c2}"
            k = 1 # Smoothing Factor.
            df[new_col] = df[c1] / (df[c2] + k)  # Avoid division by zero.
            new_QUAN_COLUMNS.add(new_col)
            new_RATIO_COLUMNS.add(new_col)
        
        # Add Humidity to Moisture Ratio Feature.
        k = 1 # smoothing factor 
        df['Humidity/Moisture'] = df['Humidity'] / (df['Moisture'] + k)  # Avoid division by zero
        new_QUAN_COLUMNS.add("Humidity/Moisture")
        new_RATIO_COLUMNS.add("Humidity/Moisture")
        
        # =========================================
        
        2.  Add 2-level Interaction term between Quantitative Columns.
            Automatically conducted.
        
        comb = list(combinations(QUAN_COLUMNS + list(new_QUAN_COLUMNS), 2))
        
        for c1, c2 in comb:
            # Check ratio columns to avoid duplicate columns.
            if c1 in new_RATIO_COLUMNS:
                if c1.split('/')[1] == c2:
                    continue
            elif c2 in new_RATIO_COLUMNS:
                if c2.split('/')[1] == c1:
                    continue
            else:
                new_col = f"{c1}*{c2}"
                df[new_col] = df[c1] * df[c2]
                new_QUAN_COLUMNS.add(new_col)
          '''  
    # Update QUAN_COLUMNS.
    QUAN_COLUMNS.extend(list(new_QUAN_COLUMNS))

    # 3. Target Label Encoding.
    le_target = LabelEncoder()
    train[TARGET] = le_target.fit_transform(train[TARGET])
    
    # Delete Unnecessary Variables for memory Efficiency.
    del new_CAT_COLUMNS, new_QUAN_COLUMNS, new_RATIO_COLUMNS, dfs
    gc.collect()
    
    return train, test, le_target

In [9]:
def prob_to_top_k_label(prob, k = 3):
    return np.argsort(prob, axis = 1)[:, -k:][:, ::-1]

In [ ]:
import numpy as np

def MAP3_score(y_true, y_pred, k=3):
    """
    Compute Mean Average Precision at k (MAP@3)
    
    y_pred : 2D array of shape (n_samples, k)
             Each row contains predicted class indices (Top-k)
    y_true : 1D array of shape (n_samples,)
             Ground truth class indices
    k      : Number of top predictions to consider
    """
    if y_pred.shape[1] != k:
        raise ValueError(f"y_pred must have shape (n_samples, {k})")
        
    weights = np.array([1.0 / (i + 1) for i in range(k)])  # MAP 정의에 더 일반적인 방식
    scores = np.sum((y_pred == y_true.reshape(-1, 1)) * weights, axis=1)
    return np.mean(scores)

In [ ]:
def make_sub(top_k_preds, le_target):
    # Load Sample Submission
    sample_submission = pd.read_csv("data/sample_submission.csv")

    # Convert top_k_preds to original target labels
    org_y_pred = le_target.inverse_transform(top_k_preds.astype(int))
    sample_submission[TARGET] = [' '.join(x) for x in org_y_pred]

    # Save submission file
    sample_submission.to_csv(f'submission/XGB_{VER}.csv', index = False)

    # Return the sample submission DataFrame
    return sample_submission

# Tuning XGBoost Parameter

- Hyperparameter tuning using `optuna`

In [12]:
# Setting up the data.
train, test, le_target = FE_for_gbdt(train, test)
train_X = train.drop(TARGET, axis=1)
train_y = train[TARGET]

In [13]:
train.head()

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name,Soil Type_Crop Type
0,37,70,36,1.0,8.0,36,4,5,4,19.0
1,27,69,65,4.0,4.0,30,6,18,4,48.0
2,29,63,32,4.0,4.0,24,12,16,2,48.0
3,35,62,54,4.0,0.0,39,12,4,0,44.0
4,35,58,43,3.0,6.0,37,2,16,5,39.0

## Parameter Setting

Using 5 folds.

- `max_depth` : 5 ~ 10
- `learning_rate` : 0.005 ~ 0.01
- `subsample` : 0.7 ~ 1.0
- `colsample_bytree` : 0.7 ~ 1.0
- `reg_alpha` : 0 ~ 1
- `reg_lambda` : 0 ~ 1

In [14]:
def objective(trial):
    xgb_params = {
        'objective' : 'multi:softprob',
        'num_class' : len(le_target.classes_),
        'eval_metric' : 'mlogloss',
        'device' : 'cuda',
        'tree_method' : 'hist',
        'max_depth' : trial.suggest_int('max_depth', 5, 10),
        'learning_rate' : trial.suggest_float('learning_rate', 0.01, 0.05),
        'subsample' : trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree' : trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'reg_alpha' : trial.suggest_float('reg_alpha', 0.5, 3.0),
        'reg_lambda' : trial.suggest_float('reg_lambda', 0.5, 3.0),
        'n_estimators' : 10000,
        'early_stopping_rounds' : 100,
        'random_state' : 42,
    }

    kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    oof_probs = np.zeros((train_X.shape[0], len(le_target.classes_)))
    y_pred_probs = np.zeros((test.shape[0], len(le_target.classes_)))

    for fold, (train_idx, val_idx) in enumerate(kf.split(train_X, train_y)):

        X_train, X_val = train_X.iloc[train_idx], train_X.iloc[val_idx]
        y_train, y_val = train_y.iloc[train_idx], train_y.iloc[val_idx]

        model = xgb.XGBClassifier(**xgb_params)
        model.fit(X_train, y_train, 
                  eval_set=[(X_val, y_val)], 
                  verbose=1000)
        oof_probs[val_idx] = model.predict_proba(X_val)
        y_pred_probs += model.predict_proba(test) / kf.n_splits
        del model, X_train, X_val, y_train, y_val
        gc.collect()

    oof_score = MAP3_score(train_y.values, prob_to_top_k_label(oof_probs))
    print(f"OOF MAP@3 Score: {oof_score:.4f}")

    return oof_score

In [15]:
# Conduct hyperparameter optimization using Optuna
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2025-06-16 19:14:49,177] A new study created in memory with name: no-name-27bf68cf-3295-429f-8cca-1743860bb318

[0]	validation_0-mlogloss:1.94583
[1000]	validation_0-mlogloss:1.92856
[2000]	validation_0-mlogloss:1.92272
[3000]	validation_0-mlogloss:1.91917
[4000]	validation_0-mlogloss:1.91675
[5000]	validation_0-mlogloss:1.91498
[6000]	validation_0-mlogloss:1.91365
[7000]	validation_0-mlogloss:1.91256
[8000]	validation_0-mlogloss:1.91173
[9000]	validation_0-mlogloss:1.91104
[9999]	validation_0-mlogloss:1.91052

/home/imcsh123/.conda/envs/rapids-25.04/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [19:20:15] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1742531908307/work/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)

[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92910
[2000]	validation_0-mlogloss:1.92350
[3000]	validation_0-mlogloss:1.92010
[4000]	validation_0-mlogloss:1.91775
[5000]	validation_0-mlogloss:1.91605
[6000]	validation_0-mlogloss:1.91476
[7000]	validation_0-mlogloss:1.91376
[8000]	validation_0-mlogloss:1.91292
[9000]	validation_0-mlogloss:1.91226
[9999]	validation_0-mlogloss:1.91175
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92876
[2000]	validation_0-mlogloss:1.92304
[3000]	validation_0-mlogloss:1.91957
[4000]	validation_0-mlogloss:1.91718
[5000]	validation_0-mlogloss:1.91549
[6000]	validation_0-mlogloss:1.91419
[7000]	validation_0-mlogloss:1.91313
[8000]	validation_0-mlogloss:1.91227
[9000]	validation_0-mlogloss:1.91158
[9999]	validation_0-mlogloss:1.91102
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92885
[2000]	validation_0-mlogloss:1.92328
[3000]	validation_0-mlogloss:1.91991
[4000]	validation_0-mlogloss:1.91764
[5000]	validation_0-mlogloss:1.91595
[6000]	validation_0-mlogloss:1.91470
[7000]	validation_0-mlogloss:1.91367
[8000]	validation_0-mlogloss:1.91282
[9000]	validation_0-mlogloss:1.91216
[9999]	validation_0-mlogloss:1.91162
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92919
[2000]	validation_0-mlogloss:1.92364
[3000]	validation_0-mlogloss:1.92025
[4000]	validation_0-mlogloss:1.91797
[5000]	validation_0-mlogloss:1.91632
[6000]	validation_0-mlogloss:1.91506
[7000]	validation_0-mlogloss:1.91409
[8000]	validation_0-mlogloss:1.91332
[9000]	validation_0-mlogloss:1.91272
[9999]	validation_0-mlogloss:1.91223

[I 2025-06-16 19:42:14,998] Trial 0 finished with value: 0.37029803921568616 and parameters: {'max_depth': 5, 'learning_rate': 0.011008557249661762, 'subsample': 0.5328285284866523, 'colsample_bytree': 0.953394198464098, 'reg_alpha': 1.4194290694412035, 'reg_lambda': 0.8265490915020658}. Best is trial 0 with value: 0.37029803921568616.

OOF MAP@3 Score: 0.3703
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.91129
[2000]	validation_0-mlogloss:1.90226
[3000]	validation_0-mlogloss:1.89864
[4000]	validation_0-mlogloss:1.89782
[4040]	validation_0-mlogloss:1.89785
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.91193
[2000]	validation_0-mlogloss:1.90315
[3000]	validation_0-mlogloss:1.89986
[3917]	validation_0-mlogloss:1.89926
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.91144
[2000]	validation_0-mlogloss:1.90251
[3000]	validation_0-mlogloss:1.89901
[4000]	validation_0-mlogloss:1.89813
[4066]	validation_0-mlogloss:1.89813
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.91183
[2000]	validation_0-mlogloss:1.90295
[3000]	validation_0-mlogloss:1.89954
[3960]	validation_0-mlogloss:1.89865
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.91216
[2000]	validation_0-mlogloss:1.90358
[3000]	validation_0-mlogloss:1.90042
[4000]	validation_0-mlogloss:1.89969
[4100]	validation_0-mlogloss:1.89975

[I 2025-06-16 20:10:00,126] Trial 1 finished with value: 0.3864427450980391 and parameters: {'max_depth': 9, 'learning_rate': 0.01321324442576024, 'subsample': 0.6582320667698587, 'colsample_bytree': 0.5175156624650156, 'reg_alpha': 1.1607455800626603, 'reg_lambda': 1.7486860621091724}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3864
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.91309
[2000]	validation_0-mlogloss:1.90935
[2124]	validation_0-mlogloss:1.90934
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91417
[2000]	validation_0-mlogloss:1.91065
[2225]	validation_0-mlogloss:1.91071
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91336
[2000]	validation_0-mlogloss:1.90966
[2198]	validation_0-mlogloss:1.90971
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91373
[2000]	validation_0-mlogloss:1.91001
[2068]	validation_0-mlogloss:1.91000
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91447
[2000]	validation_0-mlogloss:1.91114
[2191]	validation_0-mlogloss:1.91117

[I 2025-06-16 20:25:20,679] Trial 2 finished with value: 0.3723203921568628 and parameters: {'max_depth': 9, 'learning_rate': 0.015210723747845167, 'subsample': 0.5350330207917529, 'colsample_bytree': 0.9988737458101736, 'reg_alpha': 2.7736410127087465, 'reg_lambda': 0.9181768799274527}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3723
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90569
[2000]	validation_0-mlogloss:1.89979
[2445]	validation_0-mlogloss:1.89955
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90651
[2000]	validation_0-mlogloss:1.90082
[2463]	validation_0-mlogloss:1.90067
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90604
[2000]	validation_0-mlogloss:1.89998
[2466]	validation_0-mlogloss:1.89962
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.90637
[2000]	validation_0-mlogloss:1.90043
[2436]	validation_0-mlogloss:1.90001
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90705
[2000]	validation_0-mlogloss:1.90161
[2371]	validation_0-mlogloss:1.90136

[I 2025-06-16 20:42:04,361] Trial 3 finished with value: 0.3845709803921569 and parameters: {'max_depth': 9, 'learning_rate': 0.02079996170330959, 'subsample': 0.4897003282540001, 'colsample_bytree': 0.5438561882846019, 'reg_alpha': 1.1910411560106235, 'reg_lambda': 0.5981317526215761}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3846
[0]	validation_0-mlogloss:1.94582
[1000]	validation_0-mlogloss:1.92157
[2000]	validation_0-mlogloss:1.91408
[3000]	validation_0-mlogloss:1.91016
[4000]	validation_0-mlogloss:1.90799
[5000]	validation_0-mlogloss:1.90673
[6000]	validation_0-mlogloss:1.90610
[7000]	validation_0-mlogloss:1.90591
[7002]	validation_0-mlogloss:1.90591
[0]	validation_0-mlogloss:1.94582
[1000]	validation_0-mlogloss:1.92239
[2000]	validation_0-mlogloss:1.91507
[3000]	validation_0-mlogloss:1.91123
[4000]	validation_0-mlogloss:1.90909
[5000]	validation_0-mlogloss:1.90793
[6000]	validation_0-mlogloss:1.90738
[7000]	validation_0-mlogloss:1.90720
[7179]	validation_0-mlogloss:1.90719
[0]	validation_0-mlogloss:1.94582
[1000]	validation_0-mlogloss:1.92186
[2000]	validation_0-mlogloss:1.91449
[3000]	validation_0-mlogloss:1.91065
[4000]	validation_0-mlogloss:1.90845
[5000]	validation_0-mlogloss:1.90723
[6000]	validation_0-mlogloss:1.90664
[6875]	validation_0-mlogloss:1.90650
[0]	validation_0-mlogloss:1.94582
[1000]	validation_0-mlogloss:1.92204
[2000]	validation_0-mlogloss:1.91482
[3000]	validation_0-mlogloss:1.91106
[4000]	validation_0-mlogloss:1.90884
[5000]	validation_0-mlogloss:1.90767
[6000]	validation_0-mlogloss:1.90701
[7000]	validation_0-mlogloss:1.90675
[7294]	validation_0-mlogloss:1.90674
[0]	validation_0-mlogloss:1.94582
[1000]	validation_0-mlogloss:1.92244
[2000]	validation_0-mlogloss:1.91532
[3000]	validation_0-mlogloss:1.91155
[4000]	validation_0-mlogloss:1.90944
[5000]	validation_0-mlogloss:1.90831
[6000]	validation_0-mlogloss:1.90777
[6673]	validation_0-mlogloss:1.90762

[I 2025-06-16 21:09:49,372] Trial 4 finished with value: 0.3769647058823529 and parameters: {'max_depth': 7, 'learning_rate': 0.011304375226523153, 'subsample': 0.7188564830720189, 'colsample_bytree': 0.8145252824459768, 'reg_alpha': 2.351410045776033, 'reg_lambda': 1.5734939626601694}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3770
[0]	validation_0-mlogloss:1.94557
[1000]	validation_0-mlogloss:1.90431
[2000]	validation_0-mlogloss:1.90115
[2015]	validation_0-mlogloss:1.90117
[0]	validation_0-mlogloss:1.94557
[1000]	validation_0-mlogloss:1.90537
[2000]	validation_0-mlogloss:1.90232
[2048]	validation_0-mlogloss:1.90239
[0]	validation_0-mlogloss:1.94557
[1000]	validation_0-mlogloss:1.90464
[1971]	validation_0-mlogloss:1.90147
[0]	validation_0-mlogloss:1.94556
[1000]	validation_0-mlogloss:1.90484
[1972]	validation_0-mlogloss:1.90142
[0]	validation_0-mlogloss:1.94558
[1000]	validation_0-mlogloss:1.90578
[1883]	validation_0-mlogloss:1.90310

[I 2025-06-16 21:19:43,378] Trial 5 finished with value: 0.38355215686274513 and parameters: {'max_depth': 8, 'learning_rate': 0.039292949634739366, 'subsample': 0.9846651221589644, 'colsample_bytree': 0.5673904973173274, 'reg_alpha': 1.7838137517973234, 'reg_lambda': 0.507333314700102}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3836
[0]	validation_0-mlogloss:1.94550
[1000]	validation_0-mlogloss:1.90677
[1424]	validation_0-mlogloss:1.90631
[0]	validation_0-mlogloss:1.94552
[1000]	validation_0-mlogloss:1.90845
[1359]	validation_0-mlogloss:1.90799
[0]	validation_0-mlogloss:1.94551
[1000]	validation_0-mlogloss:1.90783
[1346]	validation_0-mlogloss:1.90734
[0]	validation_0-mlogloss:1.94552
[1000]	validation_0-mlogloss:1.90730
[1355]	validation_0-mlogloss:1.90673
[0]	validation_0-mlogloss:1.94553
[1000]	validation_0-mlogloss:1.90879
[1303]	validation_0-mlogloss:1.90850

[I 2025-06-16 21:26:33,836] Trial 6 finished with value: 0.37682705882352935 and parameters: {'max_depth': 8, 'learning_rate': 0.04171190030116161, 'subsample': 0.9417973823446537, 'colsample_bytree': 0.9721350614198269, 'reg_alpha': 2.9462038468579346, 'reg_lambda': 1.467355164099855}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3768
[0]	validation_0-mlogloss:1.94557
[1000]	validation_0-mlogloss:1.90398
[1111]	validation_0-mlogloss:1.90410
[0]	validation_0-mlogloss:1.94559
[1000]	validation_0-mlogloss:1.90527
[1117]	validation_0-mlogloss:1.90540
[0]	validation_0-mlogloss:1.94558
[1000]	validation_0-mlogloss:1.90462
[1155]	validation_0-mlogloss:1.90472
[0]	validation_0-mlogloss:1.94558
[1000]	validation_0-mlogloss:1.90484
[1108]	validation_0-mlogloss:1.90486
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.90547
[1114]	validation_0-mlogloss:1.90561

[I 2025-06-16 21:37:30,818] Trial 7 finished with value: 0.37926941176470585 and parameters: {'max_depth': 10, 'learning_rate': 0.03043548975150548, 'subsample': 0.8667939602340693, 'colsample_bytree': 0.6698207203659234, 'reg_alpha': 2.3649987293035633, 'reg_lambda': 2.5245098930043017}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3793
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.90843
[2000]	validation_0-mlogloss:1.90481
[2085]	validation_0-mlogloss:1.90482
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.90946
[2000]	validation_0-mlogloss:1.90600
[2128]	validation_0-mlogloss:1.90605
[0]	validation_0-mlogloss:1.94559
[1000]	validation_0-mlogloss:1.90890
[2000]	validation_0-mlogloss:1.90543
[2129]	validation_0-mlogloss:1.90543
[0]	validation_0-mlogloss:1.94559
[1000]	validation_0-mlogloss:1.90929
[2000]	validation_0-mlogloss:1.90583
[2196]	validation_0-mlogloss:1.90576
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.90994
[2000]	validation_0-mlogloss:1.90690
[2025]	validation_0-mlogloss:1.90689

[I 2025-06-16 21:45:43,589] Trial 8 finished with value: 0.3784419607843138 and parameters: {'max_depth': 7, 'learning_rate': 0.04059552290146873, 'subsample': 0.5614290675198623, 'colsample_bytree': 0.5990938531366633, 'reg_alpha': 0.698733638581051, 'reg_lambda': 1.2036991481481252}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3784
[0]	validation_0-mlogloss:1.94583
[1000]	validation_0-mlogloss:1.92862
[2000]	validation_0-mlogloss:1.92272
[3000]	validation_0-mlogloss:1.91877
[4000]	validation_0-mlogloss:1.91592
[5000]	validation_0-mlogloss:1.91375
[6000]	validation_0-mlogloss:1.91203
[7000]	validation_0-mlogloss:1.91062
[8000]	validation_0-mlogloss:1.90944
[9000]	validation_0-mlogloss:1.90844
[9999]	validation_0-mlogloss:1.90762
[0]	validation_0-mlogloss:1.94583
[1000]	validation_0-mlogloss:1.92927
[2000]	validation_0-mlogloss:1.92364
[3000]	validation_0-mlogloss:1.91991
[4000]	validation_0-mlogloss:1.91718
[5000]	validation_0-mlogloss:1.91511
[6000]	validation_0-mlogloss:1.91344
[7000]	validation_0-mlogloss:1.91210
[8000]	validation_0-mlogloss:1.91099
[9000]	validation_0-mlogloss:1.91002
[9999]	validation_0-mlogloss:1.90925
[0]	validation_0-mlogloss:1.94583
[1000]	validation_0-mlogloss:1.92891
[2000]	validation_0-mlogloss:1.92309
[3000]	validation_0-mlogloss:1.91933
[4000]	validation_0-mlogloss:1.91650
[5000]	validation_0-mlogloss:1.91438
[6000]	validation_0-mlogloss:1.91267
[7000]	validation_0-mlogloss:1.91131
[8000]	validation_0-mlogloss:1.91020
[9000]	validation_0-mlogloss:1.90925
[9999]	validation_0-mlogloss:1.90841
[0]	validation_0-mlogloss:1.94583
[1000]	validation_0-mlogloss:1.92889
[2000]	validation_0-mlogloss:1.92330
[3000]	validation_0-mlogloss:1.91960
[4000]	validation_0-mlogloss:1.91692
[5000]	validation_0-mlogloss:1.91486
[6000]	validation_0-mlogloss:1.91318
[7000]	validation_0-mlogloss:1.91183
[8000]	validation_0-mlogloss:1.91070
[9000]	validation_0-mlogloss:1.90975
[9999]	validation_0-mlogloss:1.90892
[0]	validation_0-mlogloss:1.94583
[1000]	validation_0-mlogloss:1.92930
[2000]	validation_0-mlogloss:1.92352
[3000]	validation_0-mlogloss:1.91984
[4000]	validation_0-mlogloss:1.91715
[5000]	validation_0-mlogloss:1.91510
[6000]	validation_0-mlogloss:1.91346
[7000]	validation_0-mlogloss:1.91214
[8000]	validation_0-mlogloss:1.91105
[9000]	validation_0-mlogloss:1.91015
[9999]	validation_0-mlogloss:1.90935

[I 2025-06-16 22:13:04,770] Trial 9 finished with value: 0.3737776470588234 and parameters: {'max_depth': 5, 'learning_rate': 0.01232646701415467, 'subsample': 0.9786724844920207, 'colsample_bytree': 0.7664685547589862, 'reg_alpha': 2.1875621091300186, 'reg_lambda': 0.535653873621202}. Best is trial 1 with value: 0.3864427450980391.

OOF MAP@3 Score: 0.3738
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89736
[2000]	validation_0-mlogloss:1.89240
[2059]	validation_0-mlogloss:1.89245
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89849
[2000]	validation_0-mlogloss:1.89405
[2031]	validation_0-mlogloss:1.89409
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89744
[2000]	validation_0-mlogloss:1.89281
[2023]	validation_0-mlogloss:1.89284
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89785
[2000]	validation_0-mlogloss:1.89297
[2034]	validation_0-mlogloss:1.89301
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89842
[2000]	validation_0-mlogloss:1.89420
[2031]	validation_0-mlogloss:1.89427

[I 2025-06-16 22:31:27,021] Trial 10 finished with value: 0.3924694117647058 and parameters: {'max_depth': 10, 'learning_rate': 0.024934487071891547, 'subsample': 0.6978877617199474, 'colsample_bytree': 0.40627204746269635, 'reg_alpha': 0.6341135301019687, 'reg_lambda': 2.280979078913678}. Best is trial 10 with value: 0.3924694117647058.

OOF MAP@3 Score: 0.3925
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89758
[2000]	validation_0-mlogloss:1.89262
[2051]	validation_0-mlogloss:1.89264
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89885
[2000]	validation_0-mlogloss:1.89422
[2068]	validation_0-mlogloss:1.89425
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89751
[2000]	validation_0-mlogloss:1.89266
[2030]	validation_0-mlogloss:1.89268
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89798
[2000]	validation_0-mlogloss:1.89292
[2066]	validation_0-mlogloss:1.89297
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89856
[2000]	validation_0-mlogloss:1.89424
[2032]	validation_0-mlogloss:1.89429

[I 2025-06-16 22:50:01,340] Trial 11 finished with value: 0.39258156862745097 and parameters: {'max_depth': 10, 'learning_rate': 0.024450161322014278, 'subsample': 0.6924178877102732, 'colsample_bytree': 0.4046732451199841, 'reg_alpha': 0.5295976260675789, 'reg_lambda': 2.211372813069924}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3926
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.89684
[1963]	validation_0-mlogloss:1.89238
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89804
[1964]	validation_0-mlogloss:1.89390
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.89671
[1877]	validation_0-mlogloss:1.89251
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.89740
[1960]	validation_0-mlogloss:1.89299
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.89814
[1877]	validation_0-mlogloss:1.89439

[I 2025-06-16 23:07:20,981] Trial 12 finished with value: 0.3925521568627452 and parameters: {'max_depth': 10, 'learning_rate': 0.02595856535437236, 'subsample': 0.7619805972125069, 'colsample_bytree': 0.4216896787132042, 'reg_alpha': 0.5909655323266321, 'reg_lambda': 2.468005829089773}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3926
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.89467
[1508]	validation_0-mlogloss:1.89274
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.89574
[1507]	validation_0-mlogloss:1.89392
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.89472
[1545]	validation_0-mlogloss:1.89291
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.89533
[1586]	validation_0-mlogloss:1.89314
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.89602
[1534]	validation_0-mlogloss:1.89442

[I 2025-06-16 23:21:03,076] Trial 13 finished with value: 0.39235215686274516 and parameters: {'max_depth': 10, 'learning_rate': 0.03219462045601826, 'subsample': 0.8051504013940773, 'colsample_bytree': 0.4069425291291671, 'reg_alpha': 0.5336031094873139, 'reg_lambda': 2.914187608646107}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3924
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.89941
[1521]	validation_0-mlogloss:1.89776
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.90033
[1454]	validation_0-mlogloss:1.89872
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.89935
[1539]	validation_0-mlogloss:1.89775
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.89964
[1582]	validation_0-mlogloss:1.89804
[0]	validation_0-mlogloss:1.94565
[1000]	validation_0-mlogloss:1.90036
[1534]	validation_0-mlogloss:1.89913

[I 2025-06-16 23:35:56,706] Trial 14 finished with value: 0.38686078431372545 and parameters: {'max_depth': 10, 'learning_rate': 0.026155006943012007, 'subsample': 0.7948737539461476, 'colsample_bytree': 0.4703092300735853, 'reg_alpha': 0.9231896623552438, 'reg_lambda': 2.1168959275896078}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3869
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.91998
[2000]	validation_0-mlogloss:1.91250
[3000]	validation_0-mlogloss:1.90845
[4000]	validation_0-mlogloss:1.90592
[5000]	validation_0-mlogloss:1.90427
[6000]	validation_0-mlogloss:1.90314
[7000]	validation_0-mlogloss:1.90233
[8000]	validation_0-mlogloss:1.90190
[8706]	validation_0-mlogloss:1.90166
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.92058
[2000]	validation_0-mlogloss:1.91342
[3000]	validation_0-mlogloss:1.90944
[4000]	validation_0-mlogloss:1.90696
[5000]	validation_0-mlogloss:1.90537
[6000]	validation_0-mlogloss:1.90432
[7000]	validation_0-mlogloss:1.90361
[8000]	validation_0-mlogloss:1.90326
[9000]	validation_0-mlogloss:1.90307
[9016]	validation_0-mlogloss:1.90307
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.92013
[2000]	validation_0-mlogloss:1.91293
[3000]	validation_0-mlogloss:1.90889
[4000]	validation_0-mlogloss:1.90629
[5000]	validation_0-mlogloss:1.90460
[6000]	validation_0-mlogloss:1.90343
[7000]	validation_0-mlogloss:1.90262
[8000]	validation_0-mlogloss:1.90219
[9000]	validation_0-mlogloss:1.90199
[9515]	validation_0-mlogloss:1.90192
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.92043
[2000]	validation_0-mlogloss:1.91334
[3000]	validation_0-mlogloss:1.90946
[4000]	validation_0-mlogloss:1.90694
[5000]	validation_0-mlogloss:1.90528
[6000]	validation_0-mlogloss:1.90414
[7000]	validation_0-mlogloss:1.90339
[8000]	validation_0-mlogloss:1.90289
[9000]	validation_0-mlogloss:1.90265
[9242]	validation_0-mlogloss:1.90261
[0]	validation_0-mlogloss:1.94579
[1000]	validation_0-mlogloss:1.92075
[2000]	validation_0-mlogloss:1.91364
[3000]	validation_0-mlogloss:1.90977
[4000]	validation_0-mlogloss:1.90734
[5000]	validation_0-mlogloss:1.90576
[6000]	validation_0-mlogloss:1.90473
[7000]	validation_0-mlogloss:1.90401
[8000]	validation_0-mlogloss:1.90361
[9000]	validation_0-mlogloss:1.90347
[9060]	validation_0-mlogloss:1.90348

[I 2025-06-17 00:05:58,526] Trial 15 finished with value: 0.3825756862745098 and parameters: {'max_depth': 6, 'learning_rate': 0.019686359828766764, 'subsample': 0.6358599775497928, 'colsample_bytree': 0.46758173987315005, 'reg_alpha': 1.6102620088087227, 'reg_lambda': 2.8044182786541008}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3826
[0]	validation_0-mlogloss:1.94557
[1000]	validation_0-mlogloss:1.90878
[1030]	validation_0-mlogloss:1.90880
[0]	validation_0-mlogloss:1.94558
[1000]	validation_0-mlogloss:1.90970
[1038]	validation_0-mlogloss:1.90978
[0]	validation_0-mlogloss:1.94558
[1000]	validation_0-mlogloss:1.90926
[1010]	validation_0-mlogloss:1.90931
[0]	validation_0-mlogloss:1.94557
[1000]	validation_0-mlogloss:1.90933
[1125]	validation_0-mlogloss:1.90956
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.91019
[1076]	validation_0-mlogloss:1.91045

[I 2025-06-17 00:13:33,065] Trial 16 finished with value: 0.3740768627450977 and parameters: {'max_depth': 9, 'learning_rate': 0.035212566123954035, 'subsample': 0.4049050282051687, 'colsample_bytree': 0.6702081476573409, 'reg_alpha': 0.9579587979791764, 'reg_lambda': 2.1270518457061214}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3741
[0]	validation_0-mlogloss:1.94553
[1000]	validation_0-mlogloss:1.90172
[1722]	validation_0-mlogloss:1.89993
[0]	validation_0-mlogloss:1.94554
[1000]	validation_0-mlogloss:1.90280
[1490]	validation_0-mlogloss:1.90111
[0]	validation_0-mlogloss:1.94553
[1000]	validation_0-mlogloss:1.90206
[1720]	validation_0-mlogloss:1.90031
[0]	validation_0-mlogloss:1.94554
[1000]	validation_0-mlogloss:1.90261
[1771]	validation_0-mlogloss:1.90070
[0]	validation_0-mlogloss:1.94555
[1000]	validation_0-mlogloss:1.90323
[1562]	validation_0-mlogloss:1.90168

[I 2025-06-17 00:22:07,649] Trial 17 finished with value: 0.38439803921568627 and parameters: {'max_depth': 8, 'learning_rate': 0.04609039981513589, 'subsample': 0.7632470917284048, 'colsample_bytree': 0.46655078480412215, 'reg_alpha': 0.8632713791286211, 'reg_lambda': 2.5180777740866147}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3844
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.90194
[1390]	validation_0-mlogloss:1.90098
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.90306
[1423]	validation_0-mlogloss:1.90205
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.90223
[1375]	validation_0-mlogloss:1.90131
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.90257
[1479]	validation_0-mlogloss:1.90124
[0]	validation_0-mlogloss:1.94565
[1000]	validation_0-mlogloss:1.90343
[1451]	validation_0-mlogloss:1.90257

[I 2025-06-17 00:36:59,475] Trial 18 finished with value: 0.3831380392156862 and parameters: {'max_depth': 10, 'learning_rate': 0.024997820010186925, 'subsample': 0.8648345293631502, 'colsample_bytree': 0.6164720453080843, 'reg_alpha': 1.226777565070019, 'reg_lambda': 2.513091205031321}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3831
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.91036
[1898]	validation_0-mlogloss:1.90743
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.91148
[1957]	validation_0-mlogloss:1.90839
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.91050
[1981]	validation_0-mlogloss:1.90763
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.91097
[1937]	validation_0-mlogloss:1.90787
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.91176
[1873]	validation_0-mlogloss:1.90915

[I 2025-06-17 00:51:38,858] Trial 19 finished with value: 0.3754333333333332 and parameters: {'max_depth': 9, 'learning_rate': 0.018136443281545095, 'subsample': 0.6193342971611897, 'colsample_bytree': 0.8664018146983616, 'reg_alpha': 1.8983075629073256, 'reg_lambda': 1.9467663007922307}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3754
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.91664
[2000]	validation_0-mlogloss:1.90959
[3000]	validation_0-mlogloss:1.90626
[4000]	validation_0-mlogloss:1.90463
[5000]	validation_0-mlogloss:1.90388
[5795]	validation_0-mlogloss:1.90369
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.91781
[2000]	validation_0-mlogloss:1.91095
[3000]	validation_0-mlogloss:1.90775
[4000]	validation_0-mlogloss:1.90620
[5000]	validation_0-mlogloss:1.90557
[5708]	validation_0-mlogloss:1.90538
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.91708
[2000]	validation_0-mlogloss:1.91016
[3000]	validation_0-mlogloss:1.90699
[4000]	validation_0-mlogloss:1.90545
[5000]	validation_0-mlogloss:1.90477
[5671]	validation_0-mlogloss:1.90463
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.91751
[2000]	validation_0-mlogloss:1.91063
[3000]	validation_0-mlogloss:1.90739
[4000]	validation_0-mlogloss:1.90577
[5000]	validation_0-mlogloss:1.90502
[5731]	validation_0-mlogloss:1.90479
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.91778
[2000]	validation_0-mlogloss:1.91098
[3000]	validation_0-mlogloss:1.90791
[4000]	validation_0-mlogloss:1.90651
[5000]	validation_0-mlogloss:1.90600
[5281]	validation_0-mlogloss:1.90597

[I 2025-06-17 01:11:11,145] Trial 20 finished with value: 0.3799690196078432 and parameters: {'max_depth': 6, 'learning_rate': 0.026881912432663396, 'subsample': 0.8923658649420997, 'colsample_bytree': 0.7489438632785045, 'reg_alpha': 1.461181827196395, 'reg_lambda': 2.674893990391103}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3800
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89882
[2000]	validation_0-mlogloss:1.89252
[2258]	validation_0-mlogloss:1.89245
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.89991
[2000]	validation_0-mlogloss:1.89381
[2188]	validation_0-mlogloss:1.89377
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.89870
[2000]	validation_0-mlogloss:1.89259
[2259]	validation_0-mlogloss:1.89255
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89932
[2000]	validation_0-mlogloss:1.89296
[2230]	validation_0-mlogloss:1.89292
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89983
[2000]	validation_0-mlogloss:1.89405
[2183]	validation_0-mlogloss:1.89404

[I 2025-06-17 01:33:15,147] Trial 21 finished with value: 0.39253529411764704 and parameters: {'max_depth': 10, 'learning_rate': 0.02220019882394818, 'subsample': 0.7148304353478079, 'colsample_bytree': 0.4025906323033908, 'reg_alpha': 0.5335432838656011, 'reg_lambda': 2.195522757665879}. Best is trial 11 with value: 0.39258156862745097.

OOF MAP@3 Score: 0.3925
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.89895
[2000]	validation_0-mlogloss:1.89263
[2318]	validation_0-mlogloss:1.89254
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.89975
[2000]	validation_0-mlogloss:1.89362
[2190]	validation_0-mlogloss:1.89361
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.89885
[2000]	validation_0-mlogloss:1.89268
[2357]	validation_0-mlogloss:1.89264
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.89948
[2000]	validation_0-mlogloss:1.89308
[2359]	validation_0-mlogloss:1.89305
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89985
[2000]	validation_0-mlogloss:1.89416
[2189]	validation_0-mlogloss:1.89416

[I 2025-06-17 01:55:41,834] Trial 22 finished with value: 0.39259137254901966 and parameters: {'max_depth': 10, 'learning_rate': 0.02209340191818491, 'subsample': 0.7279705831473475, 'colsample_bytree': 0.4054069304054817, 'reg_alpha': 0.5076878517364575, 'reg_lambda': 2.281788813582441}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3926
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.90069
[1701]	validation_0-mlogloss:1.89885
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.90159
[1534]	validation_0-mlogloss:1.89977
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.90057
[1537]	validation_0-mlogloss:1.89878
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.90122
[1612]	validation_0-mlogloss:1.89913
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.90190
[1522]	validation_0-mlogloss:1.90033

[I 2025-06-17 02:07:28,462] Trial 23 finished with value: 0.38583803921568643 and parameters: {'max_depth': 9, 'learning_rate': 0.032800228936883655, 'subsample': 0.7685168409907139, 'colsample_bytree': 0.49733778470841317, 'reg_alpha': 0.7955198726207251, 'reg_lambda': 1.9128781250250424}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3858
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90394
[2000]	validation_0-mlogloss:1.89763
[2330]	validation_0-mlogloss:1.89751
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90462
[2000]	validation_0-mlogloss:1.89879
[2370]	validation_0-mlogloss:1.89868
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90381
[2000]	validation_0-mlogloss:1.89778
[2314]	validation_0-mlogloss:1.89771
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90429
[2000]	validation_0-mlogloss:1.89804
[2373]	validation_0-mlogloss:1.89794
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90484
[2000]	validation_0-mlogloss:1.89919
[2117]	validation_0-mlogloss:1.89917

[I 2025-06-17 02:32:02,962] Trial 24 finished with value: 0.38727607843137235 and parameters: {'max_depth': 10, 'learning_rate': 0.016718547285152013, 'subsample': 0.6794163448634396, 'colsample_bytree': 0.45076134485657054, 'reg_alpha': 0.5025756856314922, 'reg_lambda': 2.361091274508375}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3873
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.89981
[1330]	validation_0-mlogloss:1.89886
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.90074
[1449]	validation_0-mlogloss:1.90011
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.89970
[1349]	validation_0-mlogloss:1.89890
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.90023
[1425]	validation_0-mlogloss:1.89936
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.90102
[1320]	validation_0-mlogloss:1.90034

[I 2025-06-17 02:46:30,957] Trial 25 finished with value: 0.3854886274509804 and parameters: {'max_depth': 10, 'learning_rate': 0.02827207843550024, 'subsample': 0.5841017903662016, 'colsample_bytree': 0.5169598140856129, 'reg_alpha': 1.0314015489807842, 'reg_lambda': 1.9825515653755565}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3855
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.90338
[2000]	validation_0-mlogloss:1.89521
[3000]	validation_0-mlogloss:1.89343
[3082]	validation_0-mlogloss:1.89344
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90417
[2000]	validation_0-mlogloss:1.89614
[3000]	validation_0-mlogloss:1.89468
[3015]	validation_0-mlogloss:1.89469
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.90322
[2000]	validation_0-mlogloss:1.89496
[3000]	validation_0-mlogloss:1.89324
[3074]	validation_0-mlogloss:1.89330
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90388
[2000]	validation_0-mlogloss:1.89560
[2990]	validation_0-mlogloss:1.89382
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90427
[2000]	validation_0-mlogloss:1.89647
[2991]	validation_0-mlogloss:1.89511

[I 2025-06-17 03:08:15,314] Trial 26 finished with value: 0.3917890196078432 and parameters: {'max_depth': 9, 'learning_rate': 0.02267610048273282, 'subsample': 0.7580360677983844, 'colsample_bytree': 0.43734429802979374, 'reg_alpha': 0.75493839160083, 'reg_lambda': 2.373949709973603}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3918
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.90898
[2000]	validation_0-mlogloss:1.90272
[2762]	validation_0-mlogloss:1.90184
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.90983
[2000]	validation_0-mlogloss:1.90373
[2776]	validation_0-mlogloss:1.90297
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.90910
[2000]	validation_0-mlogloss:1.90289
[2903]	validation_0-mlogloss:1.90202
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.90963
[2000]	validation_0-mlogloss:1.90339
[2813]	validation_0-mlogloss:1.90239
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.91013
[2000]	validation_0-mlogloss:1.90440
[2816]	validation_0-mlogloss:1.90372

[I 2025-06-17 03:23:07,023] Trial 27 finished with value: 0.3823501960784314 and parameters: {'max_depth': 8, 'learning_rate': 0.023129458729895434, 'subsample': 0.8040491112708718, 'colsample_bytree': 0.5824293642471491, 'reg_alpha': 0.7182311813248525, 'reg_lambda': 2.6777166305459628}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3824
[0]	validation_0-mlogloss:1.94551
[1000]	validation_0-mlogloss:1.90209
[1007]	validation_0-mlogloss:1.90212
[0]	validation_0-mlogloss:1.94552
[907]	validation_0-mlogloss:1.90344
[0]	validation_0-mlogloss:1.94550
[1000]	validation_0-mlogloss:1.90237
[1030]	validation_0-mlogloss:1.90245
[0]	validation_0-mlogloss:1.94551
[950]	validation_0-mlogloss:1.90240
[0]	validation_0-mlogloss:1.94552
[955]	validation_0-mlogloss:1.90382

[I 2025-06-17 03:33:01,675] Trial 28 finished with value: 0.3821639215686273 and parameters: {'max_depth': 10, 'learning_rate': 0.036752156192686784, 'subsample': 0.8320662608065766, 'colsample_bytree': 0.6374825462186302, 'reg_alpha': 1.007156294903577, 'reg_lambda': 1.6751702043356718}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3822
[0]	validation_0-mlogloss:1.94565
[1000]	validation_0-mlogloss:1.90201
[1893]	validation_0-mlogloss:1.89814
[0]	validation_0-mlogloss:1.94566
[1000]	validation_0-mlogloss:1.90304
[1920]	validation_0-mlogloss:1.89972
[0]	validation_0-mlogloss:1.94565
[1000]	validation_0-mlogloss:1.90223
[2000]	validation_0-mlogloss:1.89892
[2005]	validation_0-mlogloss:1.89893
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.90266
[2000]	validation_0-mlogloss:1.89904
[2031]	validation_0-mlogloss:1.89905
[0]	validation_0-mlogloss:1.94566
[1000]	validation_0-mlogloss:1.90344
[1828]	validation_0-mlogloss:1.90038

[I 2025-06-17 03:46:37,271] Trial 29 finished with value: 0.386273725490196 and parameters: {'max_depth': 9, 'learning_rate': 0.028122573421564476, 'subsample': 0.7265982128920776, 'colsample_bytree': 0.5410055494552275, 'reg_alpha': 1.3688126769168956, 'reg_lambda': 1.3611925769178643}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3863
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.90831
[1339]	validation_0-mlogloss:1.90776
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.90930
[1367]	validation_0-mlogloss:1.90875
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.90861
[1351]	validation_0-mlogloss:1.90808
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.90886
[1378]	validation_0-mlogloss:1.90827
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.90984
[1318]	validation_0-mlogloss:1.90950

[I 2025-06-17 04:00:34,093] Trial 30 finished with value: 0.3747105882352942 and parameters: {'max_depth': 10, 'learning_rate': 0.019224678907863443, 'subsample': 0.6232617670906464, 'colsample_bytree': 0.8687286330918951, 'reg_alpha': 1.3487482002207414, 'reg_lambda': 2.9735876330531554}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3747
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.89907
[2000]	validation_0-mlogloss:1.89259
[2354]	validation_0-mlogloss:1.89254
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.90006
[2000]	validation_0-mlogloss:1.89387
[2186]	validation_0-mlogloss:1.89385
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.89886
[2000]	validation_0-mlogloss:1.89264
[2258]	validation_0-mlogloss:1.89255
[0]	validation_0-mlogloss:1.94571
[1000]	validation_0-mlogloss:1.89955
[2000]	validation_0-mlogloss:1.89302
[2364]	validation_0-mlogloss:1.89292
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89999
[2000]	validation_0-mlogloss:1.89401
[2246]	validation_0-mlogloss:1.89402

[I 2025-06-17 04:21:53,514] Trial 31 finished with value: 0.39242509803921594 and parameters: {'max_depth': 10, 'learning_rate': 0.021934680256063675, 'subsample': 0.719968643827771, 'colsample_bytree': 0.40275330113578134, 'reg_alpha': 0.5924262449401407, 'reg_lambda': 2.1143735428288366}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3924
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89827
[2000]	validation_0-mlogloss:1.89265
[2187]	validation_0-mlogloss:1.89269
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89920
[2000]	validation_0-mlogloss:1.89401
[2186]	validation_0-mlogloss:1.89408
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89794
[2000]	validation_0-mlogloss:1.89268
[2031]	validation_0-mlogloss:1.89267
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89859
[2000]	validation_0-mlogloss:1.89292
[2179]	validation_0-mlogloss:1.89297
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89931
[2000]	validation_0-mlogloss:1.89418
[2098]	validation_0-mlogloss:1.89424

[I 2025-06-17 04:41:29,709] Trial 32 finished with value: 0.3924435294117648 and parameters: {'max_depth': 10, 'learning_rate': 0.023855225385455505, 'subsample': 0.6641066639022013, 'colsample_bytree': 0.4286116598764391, 'reg_alpha': 0.8012043590427347, 'reg_lambda': 2.229611694084321}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3924
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.90812
[2000]	validation_0-mlogloss:1.89994
[3000]	validation_0-mlogloss:1.89804
[3109]	validation_0-mlogloss:1.89804
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.90882
[2000]	validation_0-mlogloss:1.90085
[3000]	validation_0-mlogloss:1.89904
[3118]	validation_0-mlogloss:1.89908
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.90793
[2000]	validation_0-mlogloss:1.89991
[3000]	validation_0-mlogloss:1.89794
[3113]	validation_0-mlogloss:1.89793
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.90839
[2000]	validation_0-mlogloss:1.90019
[3000]	validation_0-mlogloss:1.89822
[3206]	validation_0-mlogloss:1.89817
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.90886
[2000]	validation_0-mlogloss:1.90124
[2960]	validation_0-mlogloss:1.89951

[I 2025-06-17 05:03:27,433] Trial 33 finished with value: 0.3868466666666668 and parameters: {'max_depth': 9, 'learning_rate': 0.016463438846621332, 'subsample': 0.7409011446323696, 'colsample_bytree': 0.48569939843281784, 'reg_alpha': 0.5086236479863819, 'reg_lambda': 1.8737324350023687}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3868
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.90001
[2000]	validation_0-mlogloss:1.89403
[2437]	validation_0-mlogloss:1.89397
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.90107
[2000]	validation_0-mlogloss:1.89547
[2296]	validation_0-mlogloss:1.89534
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.89991
[2000]	validation_0-mlogloss:1.89414
[2361]	validation_0-mlogloss:1.89403
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.90055
[2000]	validation_0-mlogloss:1.89444
[2396]	validation_0-mlogloss:1.89430
[0]	validation_0-mlogloss:1.94566
[1000]	validation_0-mlogloss:1.90112
[2000]	validation_0-mlogloss:1.89584
[2299]	validation_0-mlogloss:1.89571

[I 2025-06-17 05:19:23,372] Trial 34 finished with value: 0.3909494117647058 and parameters: {'max_depth': 9, 'learning_rate': 0.02996797941974772, 'subsample': 0.6856276972737079, 'colsample_bytree': 0.43812286548582513, 'reg_alpha': 1.115976035126724, 'reg_lambda': 2.444094538328531}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3909
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.90528
[2000]	validation_0-mlogloss:1.89783
[2548]	validation_0-mlogloss:1.89717
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.90619
[2000]	validation_0-mlogloss:1.89920
[2604]	validation_0-mlogloss:1.89865
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.90542
[2000]	validation_0-mlogloss:1.89813
[2509]	validation_0-mlogloss:1.89758
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.90581
[2000]	validation_0-mlogloss:1.89838
[2562]	validation_0-mlogloss:1.89775
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.90635
[2000]	validation_0-mlogloss:1.89934
[2545]	validation_0-mlogloss:1.89897

[I 2025-06-17 05:45:01,576] Trial 35 finished with value: 0.38713137254901964 and parameters: {'max_depth': 10, 'learning_rate': 0.014953516858959414, 'subsample': 0.6656473585431562, 'colsample_bytree': 0.5189807739356583, 'reg_alpha': 0.6474115337348928, 'reg_lambda': 2.6300893194025803}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3871
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90466
[2000]	validation_0-mlogloss:1.89628
[3000]	validation_0-mlogloss:1.89418
[3170]	validation_0-mlogloss:1.89415
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90551
[2000]	validation_0-mlogloss:1.89729
[3000]	validation_0-mlogloss:1.89550
[3018]	validation_0-mlogloss:1.89550
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90470
[2000]	validation_0-mlogloss:1.89642
[3000]	validation_0-mlogloss:1.89442
[3129]	validation_0-mlogloss:1.89443
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90511
[2000]	validation_0-mlogloss:1.89677
[3000]	validation_0-mlogloss:1.89471
[3175]	validation_0-mlogloss:1.89465
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90549
[2000]	validation_0-mlogloss:1.89764
[2966]	validation_0-mlogloss:1.89582

[I 2025-06-17 06:06:00,701] Trial 36 finished with value: 0.39044000000000006 and parameters: {'max_depth': 9, 'learning_rate': 0.021216335455280254, 'subsample': 0.5106393972422382, 'colsample_bytree': 0.40197195237539796, 'reg_alpha': 0.872174134265649, 'reg_lambda': 1.741901187913946}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3904
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.89947
[1319]	validation_0-mlogloss:1.89916
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.90067
[1319]	validation_0-mlogloss:1.90043
[0]	validation_0-mlogloss:1.94561
[1000]	validation_0-mlogloss:1.89961
[1240]	validation_0-mlogloss:1.89933
[0]	validation_0-mlogloss:1.94559
[1000]	validation_0-mlogloss:1.89984
[1328]	validation_0-mlogloss:1.89961
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.90090
[1252]	validation_0-mlogloss:1.90073

[I 2025-06-17 06:18:58,404] Trial 37 finished with value: 0.3853074509803922 and parameters: {'max_depth': 10, 'learning_rate': 0.029998902143305816, 'subsample': 0.5865837798698508, 'colsample_bytree': 0.550894469247105, 'reg_alpha': 0.5017624087054836, 'reg_lambda': 2.2637874485668634}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3853
[0]	validation_0-mlogloss:1.94577
[1000]	validation_0-mlogloss:1.91009
[2000]	validation_0-mlogloss:1.90128
[3000]	validation_0-mlogloss:1.89820
[3859]	validation_0-mlogloss:1.89773
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.91091
[2000]	validation_0-mlogloss:1.90226
[3000]	validation_0-mlogloss:1.89939
[3539]	validation_0-mlogloss:1.89908
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.91024
[2000]	validation_0-mlogloss:1.90148
[3000]	validation_0-mlogloss:1.89850
[3774]	validation_0-mlogloss:1.89800
[0]	validation_0-mlogloss:1.94577
[1000]	validation_0-mlogloss:1.91048
[2000]	validation_0-mlogloss:1.90187
[3000]	validation_0-mlogloss:1.89877
[3790]	validation_0-mlogloss:1.89826
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.91099
[2000]	validation_0-mlogloss:1.90274
[3000]	validation_0-mlogloss:1.89998
[3492]	validation_0-mlogloss:1.89973

[I 2025-06-17 06:45:04,324] Trial 38 finished with value: 0.38668549019607834 and parameters: {'max_depth': 9, 'learning_rate': 0.01441236549046886, 'subsample': 0.7089428195383464, 'colsample_bytree': 0.5017266914010645, 'reg_alpha': 1.1468632492931827, 'reg_lambda': 2.091337427419675}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3867
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91041
[2000]	validation_0-mlogloss:1.90112
[3000]	validation_0-mlogloss:1.89666
[4000]	validation_0-mlogloss:1.89475
[5000]	validation_0-mlogloss:1.89425
[5283]	validation_0-mlogloss:1.89425
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91115
[2000]	validation_0-mlogloss:1.90201
[3000]	validation_0-mlogloss:1.89788
[4000]	validation_0-mlogloss:1.89615
[4993]	validation_0-mlogloss:1.89576
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91047
[2000]	validation_0-mlogloss:1.90127
[3000]	validation_0-mlogloss:1.89694
[4000]	validation_0-mlogloss:1.89497
[4963]	validation_0-mlogloss:1.89456
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91096
[2000]	validation_0-mlogloss:1.90187
[3000]	validation_0-mlogloss:1.89752
[4000]	validation_0-mlogloss:1.89564
[5000]	validation_0-mlogloss:1.89512
[5035]	validation_0-mlogloss:1.89511
[0]	validation_0-mlogloss:1.94576
[1000]	validation_0-mlogloss:1.91128
[2000]	validation_0-mlogloss:1.90233
[3000]	validation_0-mlogloss:1.89823
[4000]	validation_0-mlogloss:1.89659
[4489]	validation_0-mlogloss:1.89635

[I 2025-06-17 07:10:13,636] Trial 39 finished with value: 0.39036627450980377 and parameters: {'max_depth': 8, 'learning_rate': 0.021007968559817663, 'subsample': 0.7783282396882438, 'colsample_bytree': 0.43588830114727223, 'reg_alpha': 2.663768435757505, 'reg_lambda': 1.7988057271106215}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3904
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.89888
[1456]	validation_0-mlogloss:1.89761
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.89979
[1451]	validation_0-mlogloss:1.89871
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.89881
[1454]	validation_0-mlogloss:1.89772
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.89934
[1471]	validation_0-mlogloss:1.89795
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.89991
[1446]	validation_0-mlogloss:1.89891

[I 2025-06-17 07:24:53,631] Trial 40 finished with value: 0.38730705882352934 and parameters: {'max_depth': 10, 'learning_rate': 0.027117801732476233, 'subsample': 0.8441425900989893, 'colsample_bytree': 0.5368930343053218, 'reg_alpha': 0.6738128341475877, 'reg_lambda': 1.5645913234912268}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3873
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89777
[2000]	validation_0-mlogloss:1.89248
[2116]	validation_0-mlogloss:1.89250
[0]	validation_0-mlogloss:1.94570
[1000]	validation_0-mlogloss:1.89894
[2000]	validation_0-mlogloss:1.89401
[2040]	validation_0-mlogloss:1.89401
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89775
[2000]	validation_0-mlogloss:1.89264
[2028]	validation_0-mlogloss:1.89268
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89830
[2000]	validation_0-mlogloss:1.89287
[2068]	validation_0-mlogloss:1.89291
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89900
[2000]	validation_0-mlogloss:1.89433
[2031]	validation_0-mlogloss:1.89436

[I 2025-06-17 07:43:57,305] Trial 41 finished with value: 0.39236941176470597 and parameters: {'max_depth': 10, 'learning_rate': 0.02411529898265716, 'subsample': 0.6948929806285334, 'colsample_bytree': 0.4044141808106165, 'reg_alpha': 0.6287052021963547, 'reg_lambda': 2.2783029261791943}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3924
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89750
[1934]	validation_0-mlogloss:1.89315
[0]	validation_0-mlogloss:1.94569
[1000]	validation_0-mlogloss:1.89856
[1960]	validation_0-mlogloss:1.89428
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89714
[1884]	validation_0-mlogloss:1.89272
[0]	validation_0-mlogloss:1.94568
[1000]	validation_0-mlogloss:1.89790
[2000]	validation_0-mlogloss:1.89325
[2074]	validation_0-mlogloss:1.89336
[0]	validation_0-mlogloss:1.94567
[1000]	validation_0-mlogloss:1.89847
[1957]	validation_0-mlogloss:1.89436

[I 2025-06-17 08:02:02,769] Trial 42 finished with value: 0.3920325490196079 and parameters: {'max_depth': 10, 'learning_rate': 0.025419084395535252, 'subsample': 0.6496892532812977, 'colsample_bytree': 0.4315498190011422, 'reg_alpha': 0.6647811204533709, 'reg_lambda': 2.3655642805896275}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3920
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.90316
[2000]	validation_0-mlogloss:1.89732
[2255]	validation_0-mlogloss:1.89732
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90383
[2000]	validation_0-mlogloss:1.89840
[2236]	validation_0-mlogloss:1.89840
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.90307
[2000]	validation_0-mlogloss:1.89743
[2177]	validation_0-mlogloss:1.89739
[0]	validation_0-mlogloss:1.94572
[1000]	validation_0-mlogloss:1.90349
[2000]	validation_0-mlogloss:1.89767
[2210]	validation_0-mlogloss:1.89757
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90409
[2000]	validation_0-mlogloss:1.89887
[2233]	validation_0-mlogloss:1.89893

[I 2025-06-17 08:24:17,239] Trial 43 finished with value: 0.3872615686274508 and parameters: {'max_depth': 10, 'learning_rate': 0.01800729103486062, 'subsample': 0.73418419219536, 'colsample_bytree': 0.4669921172137305, 'reg_alpha': 0.7989535207211029, 'reg_lambda': 2.796826219377527}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3873
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92295
[2000]	validation_0-mlogloss:1.91479
[3000]	validation_0-mlogloss:1.90954
[4000]	validation_0-mlogloss:1.90593
[5000]	validation_0-mlogloss:1.90323
[6000]	validation_0-mlogloss:1.90123
[7000]	validation_0-mlogloss:1.89967
[8000]	validation_0-mlogloss:1.89849
[9000]	validation_0-mlogloss:1.89762
[9999]	validation_0-mlogloss:1.89698
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92333
[2000]	validation_0-mlogloss:1.91539
[3000]	validation_0-mlogloss:1.91026
[4000]	validation_0-mlogloss:1.90671
[5000]	validation_0-mlogloss:1.90415
[6000]	validation_0-mlogloss:1.90226
[7000]	validation_0-mlogloss:1.90077
[8000]	validation_0-mlogloss:1.89967
[9000]	validation_0-mlogloss:1.89884
[9999]	validation_0-mlogloss:1.89821
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92289
[2000]	validation_0-mlogloss:1.91477
[3000]	validation_0-mlogloss:1.90959
[4000]	validation_0-mlogloss:1.90598
[5000]	validation_0-mlogloss:1.90330
[6000]	validation_0-mlogloss:1.90132
[7000]	validation_0-mlogloss:1.89981
[8000]	validation_0-mlogloss:1.89863
[9000]	validation_0-mlogloss:1.89776
[9999]	validation_0-mlogloss:1.89708
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92322
[2000]	validation_0-mlogloss:1.91533
[3000]	validation_0-mlogloss:1.91021
[4000]	validation_0-mlogloss:1.90666
[5000]	validation_0-mlogloss:1.90403
[6000]	validation_0-mlogloss:1.90203
[7000]	validation_0-mlogloss:1.90052
[8000]	validation_0-mlogloss:1.89936
[9000]	validation_0-mlogloss:1.89844
[9999]	validation_0-mlogloss:1.89778
[0]	validation_0-mlogloss:1.94584
[1000]	validation_0-mlogloss:1.92336
[2000]	validation_0-mlogloss:1.91548
[3000]	validation_0-mlogloss:1.91037
[4000]	validation_0-mlogloss:1.90688
[5000]	validation_0-mlogloss:1.90431
[6000]	validation_0-mlogloss:1.90243
[7000]	validation_0-mlogloss:1.90100
[8000]	validation_0-mlogloss:1.89992
[9000]	validation_0-mlogloss:1.89907
[9999]	validation_0-mlogloss:1.89852

[I 2025-06-17 09:04:55,522] Trial 44 finished with value: 0.3875047058823531 and parameters: {'max_depth': 7, 'learning_rate': 0.010275733444663798, 'subsample': 0.6984277894316497, 'colsample_bytree': 0.4001196994232212, 'reg_alpha': 0.6116003373106724, 'reg_lambda': 2.2202541488857754}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3875
[0]	validation_0-mlogloss:1.94559
[1000]	validation_0-mlogloss:1.89943
[1242]	validation_0-mlogloss:1.89910
[0]	validation_0-mlogloss:1.94560
[1000]	validation_0-mlogloss:1.90037
[1286]	validation_0-mlogloss:1.90042
[0]	validation_0-mlogloss:1.94559
[1000]	validation_0-mlogloss:1.89945
[1298]	validation_0-mlogloss:1.89953
[0]	validation_0-mlogloss:1.94557
[1000]	validation_0-mlogloss:1.89986
[1320]	validation_0-mlogloss:1.89996
[0]	validation_0-mlogloss:1.94559
[1000]	validation_0-mlogloss:1.90069
[1242]	validation_0-mlogloss:1.90080

[I 2025-06-17 09:17:40,227] Trial 45 finished with value: 0.38560705882352947 and parameters: {'max_depth': 10, 'learning_rate': 0.03220426783974235, 'subsample': 0.6047118968523059, 'colsample_bytree': 0.48388805303760857, 'reg_alpha': 0.9112023933771538, 'reg_lambda': 2.0228579280785395}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3856
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.91590
[2000]	validation_0-mlogloss:1.90948
[3000]	validation_0-mlogloss:1.90619
[4000]	validation_0-mlogloss:1.90432
[5000]	validation_0-mlogloss:1.90328
[6000]	validation_0-mlogloss:1.90273
[6661]	validation_0-mlogloss:1.90260
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.91657
[2000]	validation_0-mlogloss:1.91036
[3000]	validation_0-mlogloss:1.90722
[4000]	validation_0-mlogloss:1.90545
[5000]	validation_0-mlogloss:1.90451
[6000]	validation_0-mlogloss:1.90408
[6385]	validation_0-mlogloss:1.90400
[0]	validation_0-mlogloss:1.94562
[1000]	validation_0-mlogloss:1.91599
[2000]	validation_0-mlogloss:1.90970
[3000]	validation_0-mlogloss:1.90647
[4000]	validation_0-mlogloss:1.90461
[5000]	validation_0-mlogloss:1.90347
[6000]	validation_0-mlogloss:1.90292
[6446]	validation_0-mlogloss:1.90284
[0]	validation_0-mlogloss:1.94563
[1000]	validation_0-mlogloss:1.91646
[2000]	validation_0-mlogloss:1.91024
[3000]	validation_0-mlogloss:1.90706
[4000]	validation_0-mlogloss:1.90531
[5000]	validation_0-mlogloss:1.90415
[6000]	validation_0-mlogloss:1.90361
[6381]	validation_0-mlogloss:1.90351
[0]	validation_0-mlogloss:1.94564
[1000]	validation_0-mlogloss:1.91674
[2000]	validation_0-mlogloss:1.91057
[3000]	validation_0-mlogloss:1.90752
[4000]	validation_0-mlogloss:1.90581
[5000]	validation_0-mlogloss:1.90497
[6000]	validation_0-mlogloss:1.90450
[6284]	validation_0-mlogloss:1.90444

[I 2025-06-17 09:36:47,611] Trial 46 finished with value: 0.38167411764705894 and parameters: {'max_depth': 5, 'learning_rate': 0.04989617301307017, 'subsample': 0.8185065257713853, 'colsample_bytree': 0.45728548678582376, 'reg_alpha': 0.7494642446084684, 'reg_lambda': 2.63162889820074}. Best is trial 22 with value: 0.39259137254901966.

OOF MAP@3 Score: 0.3817
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90159
[2000]	validation_0-mlogloss:1.89331
[2911]	validation_0-mlogloss:1.89212
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90237
[2000]	validation_0-mlogloss:1.89433
[2755]	validation_0-mlogloss:1.89337
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90162
[2000]	validation_0-mlogloss:1.89337
[2728]	validation_0-mlogloss:1.89219
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90197
[2000]	validation_0-mlogloss:1.89371
[2859]	validation_0-mlogloss:1.89252
[0]	validation_0-mlogloss:1.94573
[1000]	validation_0-mlogloss:1.90255
[2000]	validation_0-mlogloss:1.89470
[2676]	validation_0-mlogloss:1.89377

[I 2025-06-17 10:02:02,799] Trial 47 finished with value: 0.3926066666666666 and parameters: {'max_depth': 10, 'learning_rate': 0.01987837563206033, 'subsample': 0.7541174218839786, 'colsample_bytree': 0.4335459907797572, 'reg_alpha': 2.075101807336464, 'reg_lambda': 1.0863161806096602}. Best is trial 47 with value: 0.3926066666666666.

OOF MAP@3 Score: 0.3926
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.90636
[2000]	validation_0-mlogloss:1.89680
[3000]	validation_0-mlogloss:1.89329
[3725]	validation_0-mlogloss:1.89275
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.90710
[2000]	validation_0-mlogloss:1.89773
[3000]	validation_0-mlogloss:1.89441
[3723]	validation_0-mlogloss:1.89398
[0]	validation_0-mlogloss:1.94574
[1000]	validation_0-mlogloss:1.90612
[2000]	validation_0-mlogloss:1.89664
[3000]	validation_0-mlogloss:1.89326
[3714]	validation_0-mlogloss:1.89279
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.90672
[2000]	validation_0-mlogloss:1.89734
[3000]	validation_0-mlogloss:1.89387
[3910]	validation_0-mlogloss:1.89331
[0]	validation_0-mlogloss:1.94575
[1000]	validation_0-mlogloss:1.90700
[2000]	validation_0-mlogloss:1.89794
[3000]	validation_0-mlogloss:1.89477
[3624]	validation_0-mlogloss:1.89440

[I 2025-06-17 10:27:57,250] Trial 48 finished with value: 0.3921325490196079 and parameters: {'max_depth': 9, 'learning_rate': 0.02008432797437684, 'subsample': 0.9206215650906759, 'colsample_bytree': 0.42681003110017735, 'reg_alpha': 2.3172375515497983, 'reg_lambda': 0.9021616352237787}. Best is trial 47 with value: 0.3926066666666666.

OOF MAP@3 Score: 0.3921
[0]	validation_0-mlogloss:1.94577
[1000]	validation_0-mlogloss:1.90796
[2000]	validation_0-mlogloss:1.89905
[3000]	validation_0-mlogloss:1.89670
[3308]	validation_0-mlogloss:1.89664
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.90864
[2000]	validation_0-mlogloss:1.90015
[3000]	validation_0-mlogloss:1.89797
[3182]	validation_0-mlogloss:1.89797
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.90795
[2000]	validation_0-mlogloss:1.89910
[3000]	validation_0-mlogloss:1.89679
[3113]	validation_0-mlogloss:1.89680
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.90837
[2000]	validation_0-mlogloss:1.89955
[3000]	validation_0-mlogloss:1.89716
[3186]	validation_0-mlogloss:1.89713
[0]	validation_0-mlogloss:1.94578
[1000]	validation_0-mlogloss:1.90873
[2000]	validation_0-mlogloss:1.90041
[3000]	validation_0-mlogloss:1.89827
[3217]	validation_0-mlogloss:1.89828

[I 2025-06-17 10:59:36,197] Trial 49 finished with value: 0.38776078431372546 and parameters: {'max_depth': 10, 'learning_rate': 0.013018947350665451, 'subsample': 0.7853091212483938, 'colsample_bytree': 0.5077232011695832, 'reg_alpha': 2.110504468549863, 'reg_lambda': 0.6701944770498849}. Best is trial 47 with value: 0.3926066666666666.

OOF MAP@3 Score: 0.3878

In [21]:
# Best Parameters
best_params = study.best_params
'''
best_params = {
        'objective' : 'multi:softprob',
        'num_class' : len(le_target.classes_),
        'eval_metric' : 'mlogloss',
        'device' : 'cuda',
        'tree_method' : 'hist',
        'max_depth' : 10,
        'learning_rate' : 0.024450161322014278,
        'subsample' : 0.6924178877102732,
        'colsample_bytree' : 0.4046732451199841,
        'reg_alpha' : 0.5295976260675789,
        'reg_lambda' : 2.211372813069924,
        'n_estimators' : 100000,
        'early_stopping_rounds' : 100,
        'random_state' : 42,
    }
'''
print("Best Parameters:", best_params)

Best Parameters: {'max_depth': 10, 'learning_rate': 0.01987837563206033, 'subsample': 0.7541174218839786, 'colsample_bytree': 0.4335459907797572, 'reg_alpha': 2.075101807336464, 'reg_lambda': 1.0863161806096602}

In [ ]:
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof_probs = np.zeros((train_X.shape[0], len(le_target.classes_)))
y_pred_probs = np.zeros((test.shape[0], len(le_target.classes_)))

for fold, (train_idx, val_idx) in enumerate(kf.split(train_X, train_y)):

    X_train, X_val = train_X.iloc[train_idx], train_X.iloc[val_idx]
    y_train, y_val = train_y.iloc[train_idx], train_y.iloc[val_idx]

    model = xgb.XGBClassifier(**best_params)
    model.fit(X_train, y_train, 
                  eval_set=[(X_val, y_val)], 
                  verbose=1000)
    oof_probs[val_idx] = model.predict_proba(X_val)
    y_pred_probs += model.predict_proba(test) / kf.n_splits

oof_score = MAP3_score(train_y.values, prob_to_top_k_label(oof_probs))
print(f"OOF MAP@3 Score: {oof_score:.4f}")

y_pred_label = prob_to_top_k_label(y_pred_probs)

[0]	validation_0-mlogloss:1.94573

In [ ]:
# Save oof files
np.save(f'oof/oof_xgb_{VER}.npy', oof_probs)

In [22]:
# Save Parameters
import json
with open(f'parameter/xgb_params_{VER}.json', 'w') as f:
    json.dump(best_params, f)